version: '3.5'

services:
  pgsql:
    image: pgsql
    build: docker/pgsql
    container_name: pgsql
    environment:
      - POSTGRES_DB=calendar
      - POSTGRES_USER=calendar_rw
      - POSTGRES_PASSWORD=calendar
      - POSTGRES_RO_USER=calendar_ro
      - POSTGRES_RO_PASSWORD=calendar

  phpstan:
    image: phpstan
    build: docker/phpstan

  phpcs:
    image: phpcs
    build: docker/phpcs

  phpcbf:
    image: phpcbf
    build: docker/phpcbf

  wait:
    image: martin/wait
