doctrine:
    dbal:
        driver: 'postgresql'
        server_version: '12.0'
        charset: 'UTF8'
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
            CompetitionCategory: App\Domain\Type\CompetitionCategory
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Entity'
                prefix: 'App\Domain\Entity'
                alias: App
